### ISSUE TITLE
关于clone到本地的配置问题

### ISSUE THREAD

**Issue by vicki-he** [Setiuo/PHP_OnlineJudge#5]
您好，请问一下哈，我如果想在本地服务器把这个项目运行起来除了按照readme里面的进行配置设置等，还需要更改什么配置嘛？或者我如果只需要在线判题（评测机）的那个模块，我应该怎么搞呢？冒昧打扰，请多担待。

**Comment by Setiuo** [comment]
评测机会轮询数据库的oj_judge_task表获取评测任务
从oj_problem_data表里获取题目测试点数据
向oj_judger表里更新评测机状态（名称，ip，运行次数，状态）
向oj_judge_compile_log表中更新编译信息
向oj_status或oj_constatus表里更新评测结果
全部都是写死的哦

**Comment by Setiuo** [comment]
> 您好，请问一下哈，我如果想在本地服务器把这个项目运行起来除了按照readme里面的进行配置设置等，还需要更改什么配置嘛？或者我如果只需要在线判题（评测机）的那个模块，我应该怎么搞呢？冒昧打扰，请多担待。

评测机会轮询数据库的oj_judge_task表获取评测任务
从oj_problem_data表里获取题目测试点数据
向oj_judger表里更新评测机状态（名称，ip，运行次数，状态）
向oj_judge_compile_log表中更新编译信息
向oj_status或oj_constatus表里更新评测结果
全部都是写死的哦，如果想单独提取出来只能按照上面的结构建表，具体你就看看oj.sql吧

**Comment by vicki-he** [comment]
好的~！感谢回答~！
