### ISSUE TITLE
关于SQL的配置问题

### ISSUE THREAD

**Issue by CCCXHR** [Setiuo/PHP_OnlineJudge#7]
在运行项目`sql`文件夹中的`oj.sql`后，网页端显示**网站维护中...马上回来~**，无法进行任何操作，请问这种问题如何解决？

**Comment by CCCXHR** [comment]
自动跳转到了`Maintain.php`

**Comment by Setiuo** [comment]
将'oj_data'表中的maintain字段对应的值改为0
另外，应该执行openjudge_new.sql，我记得有更改

**Comment by CCCXHR** [comment]
很抱歉打扰了！

刚刚我看了一下openjudge_new.sql，似乎没有添加admin账户的语句，请问是要手动添加吗？




------------------&nbsp;Original&nbsp;------------------

**Comment by CCCXHR** [comment]
谢谢！

项目的Readme里头写的是“运行openjudge.sql即可初始化数据”，可能需要更新了。😀






使用admin和123456登陆时出现了错误，望解答，谢谢。😊




------------------&nbsp;Original&nbsp;------------------

**Comment by Setiuo** [comment]
其实是openjudge.sql是新的表的结构，但是由于偷懒我并没有在新的sql文件中写上一些应该有的初始数据，需要对照oj.sql中的相关insert语句自行插入

**Comment by Setiuo** [comment]
> 谢谢！ 项目的Readme里头写的是“运行openjudge.sql即可初始化数据”，可能需要更新了。😀 使用admin和123456登陆时出现了错误，望解答，谢谢。😊
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "Setiuo/PHP_OnlineJudge" <notifications@github.com&gt;; Date:&nbsp;Fri, Nov 6, 2020 06:53 PM To:&nbsp;"Setiuo/PHP_OnlineJudge"<PHP_OnlineJudge@noreply.github.com&gt;; Cc:&nbsp;"CCC_XHR"<1448704418@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject:&nbsp;Re: [Setiuo/PHP_OnlineJudge] 关于SQL的配置问题 (#7) 将'oj_data'表中的maintain字段对应的值改为0 另外，应该执行openjudge_new.sql，我记得有更改 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

登录时出现什么错误呢

**Comment by CCCXHR** [comment]
好的，问题已经解决了！谢谢！😄




------------------&nbsp;Original&nbsp;------------------
